### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [victims/victims-hash#6]
@abn What is the license for this repo? I could  not find any info.
Cordially
Philippe

**Comment by ashcrow** [comment]
@abn Reminder: everything else is under AGPLv3+.

**Comment by abn** [comment]
@ashcrow we should probably retire this repo and add some legacy docs in README.

**Comment by ashcrow** [comment]
@abn In the meantime do you have any issue with throwing in AGPL notice? I don't mind doing it. Also, do we have something that supersedes this code or is it just no longer needed?

**Comment by abn** [comment]
@ashcrow done. This code has been deprecated since v2. The functionality has been split out into individual projects.

The 'client' implementation is https://github.com/victims/victims-client-java.
